export const AGREGAR_COMIDA_DIA = 'AGREGAR_COMIDA_DIA';
export const VACIAR_COMIDAS_DIA = 'VACIAR_COMIDAS_DIA';
export const GUARDAR_ALIMENTOS_API = 'GUARDAR_ALIMENTOS_API';
export const ELIMINAR_COMIDA_DIA = 'ELIMINAR_COMIDA_DIA';
export const MODIFICAR_GRAMOS_CONSUMIDOS_DIA = 'MODIFICAR_GRAMOS_CONSUMIDOS_DIA';
export const BOTON_CALCULAR = 'BOTON_CALCULAR';